// ===== 슬롯 카테고리 관련 상수 =====
export const SLOT_CATEGORIES = {
  '01': { label: '식비', icon: require('../assets/icons/slots/식비.png'), color: '#F1A791' },
  '02': { label: '교통비', icon: require('../assets/icons/slots/교통.png'), color: '#F5D690' },
  '03': { label: '의류/잡화', icon: require('../assets/icons/slots/잡화.png'), color: '#B8A9E4' },
  '04': { label: '카페/간식', icon: require('../assets/icons/slots/coffee.png'), color: '#B39F60' },
  '05': { label: '여가비', icon: require('../assets/icons/slots/문화생활비.png'), color: '#8ECF82' },
  '06': { label: '의료/건강', icon: require('../assets/icons/slots/건강.png'), color: '#00E3CD' },
  '07': { label: '저축', icon: require('../assets/icons/slots/저축.png'), color: '#3C8182' },
  '08': { label: '자동차비', icon: require('../assets/icons/slots/자동차비.png'), color: '#D99AC0' },
  '09': { label: '미용', icon: require('../assets/icons/slots/미용.png'), color: '#E7A396' },
  '10': { label: '취미', icon: require('../assets/icons/slots/취미.png'), color: '#F9F4BC' },
  '11': { label: '보험비', icon: require('../assets/icons/slots/보험비.png'), color: '#88CDD5' },
  '12': { label: '통신비', icon: require('../assets/icons/slots/통신비.png'), color: '#AEDAD7' },
  '13': { label: '주거비', icon: require('../assets/icons/slots/주거비.png'), color: '#5E9DDE' },
  '14': { label: '구독비', icon: require('../assets/icons/slots/구독비.png'), color: '#F3C9E4' },
  '15': { label: '육아비', icon: require('../assets/icons/slots/육아비.png'), color: '#E7AAD7' },
  '16': { label: '용돈/선물', icon: require('../assets/icons/slots/용돈.png'), color: '#969A60' },
  '17': { label: '반려동물', icon: require('../assets/icons/slots/반려동물.png'), color: '#F7A978' },
  '18': { label: '데이트', icon: require('../assets/icons/slots/데이트비용.png'), color: '#F26C61' },
  '19': { label: '세금', icon: require('../assets/icons/slots/세금.png'), color: '#AD9291' },
  '20': { label: '교육비', icon: require('../assets/icons/slots/교육비.png'), color: '#98D0F5' },
  '21': { label: '경조사', icon: require('../assets/icons/slots/경조사비.png'), color: '#817288' },
  '22': { label: '회비', icon: require('../assets/icons/slots/회비.png'), color: '#851F41' },
  '23': { label: '후원', icon: require('../assets/icons/slots/후원.png'), color: '#83A061' },
  '24': { label: '여행/숙박', icon: require('../assets/icons/slots/숙박비.png'), color: '#CAD892' },
} as const;
 